package config

const (
	RTokenSeriesModuleId     = "RTokenSeries"
	LiquidityBondEventId     = "LiquidityBond"
	NominationUpdatedEventId = "NominationUpdated"
	ValidatorUpdatedEventId  = "ValidatorUpdated"
	StorageBondRecords       = "BondRecords"
	StorageBondStates        = "BondStates"
	MethodExecuteBondRecord  = "RTokenSeries.execute_bond_record"
	StorageNominated         = "Nominated"

	RtokenVoteModuleId         = "RTokenVotes"
	StorageVotes               = "Votes"
	MethodRacknowledgeProposal = "RTokenVotes.acknowledge_proposal"

	RTokenLedgerModuleId       = "RTokenLedger"
	EraPoolUpdatedEventId      = "EraPoolUpdated"
	StorageChainEras           = "ChainEras"
	StorageCurrentEraSnapShots = "CurrentEraSnapShots"
	StorageEraSnapShots        = "EraSnapShots"
	StorageLeastBond           = "LeastBond"
	MethodSetChainEra          = "RTokenLedger.set_chain_era"
	MethodBondReport           = "RTokenLedger.bond_report"
	MethodNewBondReport        = "RTokenLedger.new_bond_report"
	MethodActiveReport         = "RTokenLedger.active_report"
	MethodNewActiveReport      = "RTokenLedger.new_active_report"
	MethodBondAndReportActive  = "RTokenLedger.bond_and_report_active"
	MethodWithdrawReport       = "RTokenLedger.withdraw_report"
	MethodTransferReport       = "RTokenLedger.transfer_report"
	BondReportedEventId        = "BondReported"
	ActiveReportedEventId      = "ActiveReported"
	WithdrawReportedEventId    = "WithdrawReported"
	TransferReportedEventId    = "TransferReported"
	StorageSubAccounts         = "SubAccounts"
	StorageMultiThresholds     = "MultiThresholds"
	StorageBondedPools         = "BondedPools"
	StorageSnapshots           = "Snapshots"
	StoragePoolUnbonds         = "PoolUnbonds"
	SignaturesEnoughEventId    = "SignaturesEnough"
	StorageSignatures          = "Signatures"
	SubmitSignatures           = "RTokenSeries.submit_signatures"
)
